<x-table.index>
    <x-slot name="title">{{ __('Organization Experience') }}</x-slot>


    <x-slot name="header">
        <b>{{ $employee->full_name ?? '' }}</b>
    </x-slot>
    <x-slot name="header_toolbar">

    </x-slot>

    <x-slot name="toolbar">
        <x-table.add-button :label="__('Add')" :href="route('employee-payslip-generate.create')" />
    </x-slot>


    <x-slot name="body">

        @if (count($list) == 0)
            <x-table.empty />
        @else
            <div class="table-responsive">
                <x-table.table>
                    <x-slot name="header">
                        <th>{{ __('ID') }}</th>
                        <th>{{ __('Company') }}</th>
                        <th>{{ __('Month/Year') }}</th>
                        <th>{{ __('Total Employee Generated') }}</th>
                        <th>{{ __('Generated By') }}</th>
                        <th>{{ __('Generated At') }}</th>
                        <th class="text-end">{{ __('Actions') }}</th>
                    </x-slot>

                    <x-slot name="body">
                        @foreach ($list as $key => $value)
                            <tr>
                                <td>{{ ($list->currentPage() - 1) * $list->perPage() + $key + 1 }}</td>
                                <td>{{ $value->company->name ?? '' }}</td>
                                <td>{{ $value->month ?? '' }}/{{ $value->year ?? '' }}</td>
                                <td>{{ number_format($value->data_generate_total ?? 0, ",",".") }}</td>
                                <td></td>
                                <td></td>
                                <td class="text-end">
                                    <x-table.actions>

                                        <x-table.edit-button :href="route('organization-experience.edit', [$employee, $value->id])" />
                                        <x-table.delete-button :href="route('organization-experience.destroy', [$employee, $value->id])" />
                                    </x-table.actions>
                                </td>
                            </tr>
                        @endforeach


                    </x-slot>
                </x-table.table>

                {{ $list->links() }}
            </div>
        @endif
    </x-slot>
</x-table.index>
