<x-card>
  <x-slot name="title">{{ __("Generate Payslip") }}</x-slot>
  <x-slot name="header">
    <b>{{ __("Generate Payslip") }}</b>
  </x-slot>
  <x-slot name="toolbar">
    <x-table.filter-dropdown :company="true" :daterange="true" :monthyear="true" />
    <x-table.add-button
      :label="__('Add')"
      :href="route('employee-payslip-generate.create')" />
  </x-slot>

  <x-slot name="body">
    @if (count($list) == 0)
    <x-table.empty />
    @else
    <div class="table-responsive">
      <x-table.table>
        <x-slot name="header">
          <th>{{ __("ID") }}</th>
          <th>{{ __("Company") }}</th>
          <th>{{ __("Month/Year") }}</th>
          <th>{{ __("Total Employee Generated") }}</th>
          <th>{{ __("Generated By") }}</th>
          <th>{{ __("Generated At") }}</th>
          <th class="text-end">{{ __("Actions") }}</th>
        </x-slot>

        <x-slot name="body">
          @foreach ($list as $key => $value)
          <tr>
            <td>
              {{ ($list->currentPage() - 1) * $list->perPage() + $key + 1 }}
            </td>
            <td>{{ $value->company->name ?? '' }}</td>
            <td>{{ $value->month ?? '' }}/{{ $value->year ?? '' }}</td>
            <td>
              {{ number_format($value->data_generate_total ?? 0, 0, ',', '.') }}
              {{ $value->data_generate_total > 1 ? __('Employees') : __('Employee') }}
            </td>
            <td>{{ $value->created_by->full_name ?? '-' }}</td>
            <td>{{ $value->created_at->format('d M Y') }}</td>
            <td class="text-end">
              <a href="{{ route('payslip-generate-detail', [$value->id]) }}">
                @include('icons.eye')
              </a>
            </td>
          </tr>
          @endforeach
        </x-slot>
      </x-table.table>

      {{ $list->appends(request()->query())->links() }}
    </div>
    @endif
  </x-slot>
</x-card>
