<?php

namespace App\Models;

use App\Traits\SearchTrait;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ptkp extends Model
{
    use HasFactory;
    use HasUuids;

    use SearchTrait;


    protected $primaryKey = 'id'; // Use 'id' as the primary key
    public $incrementing = false;  // Disable auto-incrementing
    protected $keyType = 'string'; // Since UUID is a string


    public $fillable = [
        'type_ter',
        'value_start',
        'value_end',
        'value',
        'notes',
    ];

    public $rules = [
        'type_ter'  => 'required',
        'value_start'  => 'required',
        'value_end'  => 'required',
        'value'  => 'required',
        'notes'  => '',
    ];


    public static function dummy_data() : array
    {
        $insert = [
            [
                'type_ter' => 'TER-A',
                'value_start' => 0,
                'value_end' => 5400000,
                'value' => '0,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 5400001,
                'value_end' => 5650000,
                'value' => '0,25',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 5650001,
                'value_end' => 5950000,
                'value' => '0,50',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 5950001,
                'value_end' => 6300000,
                'value' => '0,75',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 6300001,
                'value_end' => 6750000,
                'value' => '1,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 6750001,
                'value_end' => 7500000,
                'value' => '1,25',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 7500001,
                'value_end' => 8550000,
                'value' => '1,50',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 8550001,
                'value_end' => 9650000,
                'value' => '1,75',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 9650001,
                'value_end' => 10050000,
                'value' => '2,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 9650001,
                'value_end' => 10050000,
                'value' => '2,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 10050001,
                'value_end' => 10350000,
                'value' => '2,25',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 10350001,
                'value_end' => 10700000,
                'value' => '2,50',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 10700001,
                'value_end' => 11050000,
                'value' => '3,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 11050001,
                'value_end' => 11600000,
                'value' => '3,50',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 11600001,
                'value_end' => 12500000,
                'value' => '4,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 12500001,
                'value_end' => 13750000,
                'value' => '5,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 13750001,
                'value_end' => 15100000,
                'value' => '6,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 15100001,
                'value_end' => 16950000,
                'value' => '7,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 16950001,
                'value_end' => 19750000,
                'value' => '8,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 19750001,
                'value_end' => 24150000,
                'value' => '9,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 19750001,
                'value_end' => 24150000,
                'value' => '9,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 24150001,
                'value_end' => 26450000,
                'value' => '10,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 26450001,
                'value_end' => 28000000,
                'value' => '11,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 28000001,
                'value_end' => 30050000,
                'value' => '12,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 30050001,
                'value_end' => 32400000,
                'value' => '13,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 32400001,
                'value_end' => 35400000,
                'value' => '14,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 35400001,
                'value_end' => 39100000,
                'value' => '15,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 39100001,
                'value_end' => 43850000,
                'value' => '16,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 43850001,
                'value_end' => 47800000,
                'value' => '17,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 43850001,
                'value_end' => 47800000,
                'value' => '18,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 51400001,
                'value_end' => 56300000,
                'value' => '19,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 51400001,
                'value_end' => 56300000,
                'value' => '19,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 56300001,
                'value_end' => 62200000,
                'value' => '20,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 62200001,
                'value_end' => 68600000,
                'value' => '21,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 68600001,
                'value_end' => 77500000,
                'value' => '22,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 77500001,
                'value_end' => 89000000,
                'value' => '23,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 89000001,
                'value_end' => 103000000,
                'value' => '24,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 103000001,
                'value_end' => 125000000,
                'value' => '25,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 125000001,
                'value_end' => 157000000,
                'value' => '26,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 157000001,
                'value_end' => 206000000,
                'value' => '27,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 206000001,
                'value_end' => 337000000,
                'value' => '28,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 337000001,
                'value_end' => 454000000,
                'value' => '29,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 454000001,
                'value_end' => 550000000,
                'value' => '30,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 550000001,
                'value_end' => 695000000,
                'value' => '31,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 695000001,
                'value_end' => 910000000,
                'value' => '32,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 910000001,
                'value_end' => 1400000000,
                'value' => '33,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 1400000000,
                'value_end' => 99999999999,
                'value' => '34,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 0,
                'value_end' => 6200000,
                'value' => '0,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 6200001,
                'value_end' => 6500000,
                'value' => '0,25',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 6500001,
                'value_end' => 6850000,
                'value' => '0,50',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 6850001,
                'value_end' => 7300000,
                'value' => '0,75',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 7300001,
                'value_end' => 9200000,
                'value' => '1,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 1400000000,
                'value_end' => 99999999999,
                'value' => '34,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 0,
                'value_end' => 6200000,
                'value' => '0,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 6200001,
                'value_end' => 6500000,
                'value' => '0,25',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 6500001,
                'value_end' => 6850000,
                'value' => '0,50',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 6850001,
                'value_end' => 7300000,
                'value' => '0,75',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 7300001,
                'value_end' => 9200000,
                'value' => '1,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 9200001,
                'value_end' => 10750000,
                'value' => '1,50',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 10750001,
                'value_end' => 11250000,
                'value' => '2,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 11250001,
                'value_end' => 11600000,
                'value' => '2,50',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 11600001,
                'value_end' => 12600000,
                'value' => '3,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 12600001,
                'value_end' => 13600000,
                'value' => '4,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 13600001,
                'value_end' => 14950000,
                'value' => '5,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 14950001,
                'value_end' => 16480000,
                'value' => '6,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 16400001,
                'value_end' => 18450000,
                'value' => '7,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 18450001,
                'value_end' => 21850000,
                'value' => '8,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 21850001,
                'value_end' => 26000000,
                'value' => '9,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 26000001,
                'value_end' => 27700000,
                'value' => '10,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 27700001,
                'value_end' => 29350000,
                'value' => '11,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 29350001,
                'value_end' => 31450000,
                'value' => '12,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 31450001,
                'value_end' => 33950000,
                'value' => '13,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 33950001,
                'value_end' => 37100000,
                'value' => '14,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 37100001,
                'value_end' => 41100000,
                'value' => '15,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 41100001,
                'value_end' => 45800000,
                'value' => '16,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 45800001,
                'value_end' => 49500000,
                'value' => '17,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 49500001,
                'value_end' => 53800000,
                'value' => '18,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 53800001,
                'value_end' => 58500000,
                'value' => '19,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-A',
                'value_start' => 1400000000,
                'value_end' => 99999999999,
                'value' => '34,00',
                'notes' => 'PTKP: TK/0 (54 Juta); TK/1 & K/0 (58,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 0,
                'value_end' => 6200000,
                'value' => '0,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            // ... (previous TER-B entries) ...
            [
                'type_ter' => 'TER-B',
                'value_start' => 53800001,
                'value_end' => 58500000,
                'value' => '19,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 58500001,
                'value_end' => 64000000,
                'value' => '20,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 64000001,
                'value_end' => 71000000,
                'value' => '21,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 71000001,
                'value_end' => 80000000,
                'value' => '22,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 80000001,
                'value_end' => 93000000,
                'value' => '23,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 93000001,
                'value_end' => 109000000,
                'value' => '24,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 109000001,
                'value_end' => 129000000,
                'value' => '25,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 129000001,
                'value_end' => 163000000,
                'value' => '26,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 163000001,
                'value_end' => 211000000,
                'value' => '27,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 211000001,
                'value_end' => 374000000,
                'value' => '28,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 374000001,
                'value_end' => 459000000,
                'value' => '29,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 459000001,
                'value_end' => 555000000,
                'value' => '30,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 555000001,
                'value_end' => 704000000,
                'value' => '31,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 704000001,
                'value_end' => 957000000,
                'value' => '32,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 957000001,
                'value_end' => 1405000000,
                'value' => '33,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 1405000000,
                'value_end' => 99999999999,
                'value' => '34,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 0,
                'value_end' => 6600000,
                'value' => '0,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 6600001,
                'value_end' => 6950000,
                'value' => '0,25',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 6950001,
                'value_end' => 7350000,
                'value' => '0,50',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 7350001,
                'value_end' => 7800000,
                'value' => '0,75',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 7800001,
                'value_end' => 8850000,
                'value' => '1,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 8850001,
                'value_end' => 9800000,
                'value' => '1,25',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 9800001,
                'value_end' => 10950000,
                'value' => '1,50',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 10950001,
                'value_end' => 11200000,
                'value' => '1,75',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 11200001,
                'value_end' => 12050000,
                'value' => '2,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 12050001,
                'value_end' => 12950000,
                'value' => '3,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 12950001,
                'value_end' => 14150000,
                'value' => '4,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 14150001,
                'value_end' => 15550000,
                'value' => '5,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 15550001,
                'value_end' => 17050000,
                'value' => '6,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 17050001,
                'value_end' => 19500000,
                'value' => '7,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 19500001,
                'value_end' => 22700000,
                'value' => '8,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-B',
                'value_start' => 1405000000,
                'value_end' => 99999999999,
                'value' => '34,00',
                'notes' => 'PTKP: TK/2 & K/1 (63 Juta); TK/3 & K/2 (67,5 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 0,
                'value_end' => 6600000,
                'value' => '0,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 6600001,
                'value_end' => 6950000,
                'value' => '0,25',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 6950001,
                'value_end' => 7350000,
                'value' => '0,50',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 7350001,
                'value_end' => 7800000,
                'value' => '0,75',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 7800001,
                'value_end' => 8850000,
                'value' => '1,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 8850001,
                'value_end' => 9800000,
                'value' => '1,25',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 9800001,
                'value_end' => 10950000,
                'value' => '1,50',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 10950001,
                'value_end' => 11200000,
                'value' => '1,75',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 11200001,
                'value_end' => 12050000,
                'value' => '2,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 12050001,
                'value_end' => 12950000,
                'value' => '3,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 12950001,
                'value_end' => 14150000,
                'value' => '4,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 14150001,
                'value_end' => 15550000,
                'value' => '5,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 15550001,
                'value_end' => 17050000,
                'value' => '6,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 17050001,
                'value_end' => 19500000,
                'value' => '7,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 19500001,
                'value_end' => 22700000,
                'value' => '8,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 22700001,
                'value_end' => 26600000,
                'value' => '9,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 26600001,
                'value_end' => 28100000,
                'value' => '10,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 28100001,
                'value_end' => 30100000,
                'value' => '11,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 30100001,
                'value_end' => 32600000,
                'value' => '12,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 32600001,
                'value_end' => 35400000,
                'value' => '13,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 35400001,
                'value_end' => 38900000,
                'value' => '14,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 38900001,
                'value_end' => 43000000,
                'value' => '15,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 43000001,
                'value_end' => 47400000,
                'value' => '16,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 47400001,
                'value_end' => 51200000,
                'value' => '17,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 51200001,
                'value_end' => 55800000,
                'value' => '18,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 55800001,
                'value_end' => 60400000,
                'value' => '19,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 60400001,
                'value_end' => 66700000,
                'value' => '20,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 66700001,
                'value_end' => 74500000,
                'value' => '21,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 74500001,
                'value_end' => 83200000,
                'value' => '22,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 83200001,
                'value_end' => 95600000,
                'value' => '23,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 95600001,
                'value_end' => 110000000,
                'value' => '24,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 110000001,
                'value_end' => 134000000,
                'value' => '25,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 134000001,
                'value_end' => 169000000,
                'value' => '26,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 169000001,
                'value_end' => 221000000,
                'value' => '27,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 221000001,
                'value_end' => 390000000,
                'value' => '28,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 390000001,
                'value_end' => 463000000,
                'value' => '29,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 463000001,
                'value_end' => 561000000,
                'value' => '30,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 561000001,
                'value_end' => 709000000,
                'value' => '31,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 709000001,
                'value_end' => 965000000,
                'value' => '32,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 965000001,
                'value_end' => 1419000000,
                'value' => '33,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
            [
                'type_ter' => 'TER-C',
                'value_start' => 1419000000,
                'value_end' => 99999999999,
                'value' => '34,00',
                'notes' => 'PTKP: K/3 (72 Juta)',
            ],
        ];


        $insert = collect($insert)->map(function($row){
            $row['value'] = str_replace(",",".", $row['value']);
            return $row;
        })->all();


        return $insert;
    }
}
